name: cicd.yml
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  call-test-workflow:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  deploy:
    needs: call-test-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        working-directory: ./multimodal-rag/infrastructure
        run: |
          uv sync
          sudo npm i -g aws-cdk

      - name: Deploy
        working-directory: ./multimodal-rag/infrastructure
        run: |
          uv run cdk deploy