on:
  - push
  - workflow_call


jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: build the test image
        working-directory: ./multimodal-rag/
        run: |
          docker compose -f .docker/compose.yaml build

      - name: save image
        run: |
          docker save mm-rag:test -o ${{ runner.temp }}/image.tar

      - name: upload test image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mm-rag-test
          path: ${{ runner.temp }}/image.tar


  test:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load the test-container
        uses: actions/download-artifact@v4
        with:
          name: mm-rag-test
          path: ${{ runner.temp }}

      - name: Spin up test-container
        run: |
          docker load --input ${{ runner.temp }}/image.tar

      - name: Run tests
        working-directory: ./multimodal-rag/
        run: |
          docker compose -f ./.docker/compose.yaml up