on:
  - push
  - workflow_call


jobs:

  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-credentials
          path: ~/.aws/credentials

  build-test:
    runs-on: ubuntu-latest
    needs: configure-aws

    steps:
      - uses: actions/checkout@v2

      - name: load aws credentials
        uses: actions/download-artifact@v4
        with:
          name: aws-credentials
          path: ~/.aws

      - name: build the test image
        working-directory: ./multimodal-rag/
        run: |
          docker compose -f .docker/compose.yaml build

      - name: save image
        run: |
          docker save mm-rag:test -o ${{ runner.temp }}/image.tar

      - name: upload test image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mm-rag-test
          path: ${{ runner.temp }}/image.tar

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: load aws credentials
        uses: actions/download-artifact@v4
        with:
          name: aws-credentials
          path: ~/.aws

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync
          uv add tox-gh-actions

      - name: Test with tox
        run: uvx tox -p