name: tests.yml
on:
   - push
   - pull_request

jobs:

  build-dev:
    runs-on: ubuntu latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        working-directory: ./multimodal-rag/
        run: |
          docker compose -f .docker/compose.yaml build

      - name: save image to file
        run: |
          docker save mm-rag-dev:latest -o image.tar

      - name: upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
