name: tests.yml
on:
   - push

jobs:

  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        working-directory: ./multimodal-rag/
        run: |
          docker compose -f .docker/compose.yaml build

      - name: save image to file
        run: |
          docker save mm-rag:test -o image.tar

      - name: upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-image
          path: ${{ runner.temp }}/image.tar

  test:
    runs-on: ubuntu-latest
    needs: build-dev

    steps:
      - name: Download test-image from build-dev job

        uses: actions/download-artifact@v4
        with:
          name: test-image
          path: ${{ runner.temp }}/image.tar

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/image.tar
