on:
  - push
  - workflow_call


jobs:

  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-credentials
          path: ~/.aws/credentials

  test:
    runs-on: ubuntu-latest
    needs: configure-aws

    steps:
      - uses: actions/checkout@v2

      - name: setup python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: load aws credentials
        uses: actions/download-artifact@v4
        with:
          name: aws-credentials
          path: ~/.aws

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync
          uv add tox-gh-actions
          curl -LO https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.15.0/tectonic-0.15.0-x86_64-unknown-linux-musl.tar.gz && \
          tar -xzf tectonic-0.15.0-x86_64-unknown-linux-musl.tar.gz && \
          mv tectonic /usr/local/bin/tectonic && \
          chmod +x /usr/local/bin/tectonic && \
          rm tectonic-0.15.0-x86_64-unknown-linux-musl.tar.gz

      - name: Test with tox
        working-directory: multimodal-rag/
        run: uvx tox -p

      - name: Test with nose2
        working-directory: multimodal-rag/
        run: uv run nose2